### ISSUE TITLE
Добавить сайт в социальные закладки

### ISSUE THREAD

**Issue by galchenok** [octoanswers/marketing-backlog#15]
- [ ] memori.ru
- [ ] moemesto.ru
- [ ] bobrdobr.ru
- [ ] rumarkz.ru
- [ ] myscoop.ru
- [ ] mister-wong.ru
- [ ] 100zakladok.ru
- [ ] bookmark.searchengines.ru

**Comment by gomzyakov** [comment]
@galchenok Сомневаюсь, что добавление главной страницы http://askwiki.org/ в сервисы социальных закладок хоть как-то повлияет на ранжирование страниц.

**Comment by galchenok** [comment]
@gomzyakov Может и не повлияет, но инструментов продвижения без бюджета итак не много. Попытка не пытка.

**Comment by gomzyakov** [comment]
Ок
