### ISSUE TITLE
Привлеч 100 посетителей через Яндекс.Директ

### ISSUE THREAD

**Issue by gomzyakov** [octoanswers/marketing-backlog#7]
**Гипотеза**

Стоимость привлечения одного зарегистрированного пользователя -- 50 рублей.

**Действия**

Проанализируем несколько запросов с Директа по гарантированным показам:

Предложенные фразы | Примерное количество запросов | Примерное количество показов в месяц (по гарантии)* | Примерное количество переходов в месяц (по гарантии)* | Примерная установленная цена клика (по гарантии), руб. | Примерная списываемая цена клика (по гарантии), руб. | Примерный бюджет, руб. (по гарантии)
-- | -- | -- | -- | -- | -- | --
википедия ответы -вопрос | 995 | 203 | 2 | 13.10 | 0.90 | 1.80
вопрос отвечать -!на | 14446 | 5218 | 21 | 20.00 | 4.10 | 86.10
ответы +на вопросы | 977429 | 472130 | 3354 | 5.50 | 1.10 | 3689.40
сайт вопросов и ответов | 5372 | 2263 | 19 | 50.60 | 4.10 | 77.90
Итого с учетом выбранных позиций** | 998242 | 479814 | 3396 |   |   | 3855.20

Интересен только **сайт вопросов и ответов**

**Цели**

* Меряем количество заданных вопросов
* Меряем глубину просмотров

**Comment by galchenok** [comment]
До того как привлекать посетителей, необходимо выработать **метрики** которые будем замерять.

**Comment by gomzyakov** [comment]
@galchenok Займись выработкой ключевых действий.
